import { ExtendedComplaint, SolutionRecord } from '../types/schema';

export const HISTORICAL_SOLUTIONS: SolutionRecord[] = [
    {
        category: 'Water Supply',
        problemPattern: 'leakage',
        effectiveSolution: 'Replace old PVC joints with reinforced steel couplers and recalibrate pressure valves.',
        lastUsed: '2026-02-15',
        successRate: 0.92
    },
    {
        category: 'Electricity',
        problemPattern: 'transformer',
        effectiveSolution: 'Replace blown capacitor in the transformer unit and install surge protection.',
        lastUsed: '2026-03-01',
        successRate: 0.85
    },
    {
        category: 'Infrastructure',
        problemPattern: 'potholes',
        effectiveSolution: 'Deploy bituminous cold-mix repair team and monitor for 72 hours for drainage issues.',
        lastUsed: '2026-03-10',
        successRate: 0.88
    },
    {
        category: 'Health',
        problemPattern: 'vaccine',
        effectiveSolution: 'Reroute cold-chain logistics from the central hub and prioritize district-level storage nodes.',
        lastUsed: '2026-03-20',
        successRate: 0.95
    }
];

export const MOCK_COMPLAINTS: Partial<ExtendedComplaint>[] = [
    {
        "id": "CPG-2023-001",
        "citizenName": "Deepak Patil",
        "department": "MoRD",
        "subject": "Street light tr...",
        "category": "Electricity",
        "description": "Street light transformer failure. Urgent attention needed in Gachibowli area near the local landmark.",
        "location": "Ward 8",
        "ward": "Ward 15",
        "dateFiled": "21/10/23",
        "status": "Escalated",
        "lastAction": "Escalated"
    },
    {
        "id": "CPG-2023-002",
        "citizenName": "Vikram Malhotra",
        "department": "MoE",
        "subject": "Primary school ...",
        "category": "Education",
        "description": "Primary school building needs repair. Urgent attention needed in Gachibowli area near the local landmark.",
        "location": "Salt Lake",
        "ward": "Ward 18",
        "dateFiled": "21/10/23",
        "status": "Escalated",
        "lastAction": "Verify"
    },
    {
        "id": "CPG-2023-003",
        "citizenName": "Rakesh Verma",
        "department": "MoHFW",
        "subject": "Vaccine deliver...",
        "category": "Health",
        "description": "Vaccine delivery delay. Urgent attention needed in Ward 8 area near the local landmark.",
        "location": "Indiranagar",
        "ward": "Ward 11",
        "dateFiled": "21/10/23",
        "status": "Escalated",
        "lastAction": "Verify"
    },
    {
        "id": "CPG-2023-004",
        "citizenName": "Suresh Reddy",
        "department": "MoE",
        "subject": "Primary school ...",
        "category": "Education",
        "description": "Primary school building needs repair. Urgent attention needed in Ward 5 area near the local landmark.",
        "location": "Ward 12",
        "ward": "Ward 1",
        "dateFiled": "21/10/23",
        "status": "Processing",
        "lastAction": "Resolved"
    },
    {
        "id": "CPG-2023-005",
        "citizenName": "Rakesh Verma",
        "department": "MoE",
        "subject": "Primary school ...",
        "category": "Education",
        "description": "Primary school building needs repair. Urgent attention needed in Indiranagar area near the local landmark.",
        "location": "Ward 12",
        "ward": "Ward 18",
        "dateFiled": "21/10/23",
        "status": "Processing",
        "lastAction": "Resolved"
    },
    {
        "id": "CPG-2023-006",
        "citizenName": "Vikram Malhotra",
        "department": "MoHFW",
        "subject": "Vaccine deliver...",
        "category": "Health",
        "description": "Vaccine delivery delay. Urgent attention needed in Salt Lake area near the local landmark.",
        "location": "Indiranagar",
        "ward": "Ward 20",
        "dateFiled": "21/10/23",
        "status": "Processing",
        "lastAction": "Escalated"
    },
    {
        "id": "CPG-2023-007",
        "citizenName": "Anjali Gupta",
        "department": "MoE",
        "subject": "Scholarship pen...",
        "category": "Education",
        "description": "Scholarship pending since last semester. Urgent attention needed in Indiranagar area near the local landmark.",
        "location": "Ward 5",
        "ward": "Ward 5",
        "dateFiled": "21/10/23",
        "status": "Escalated",
        "lastAction": "Resolved"
    },
    {
        "id": "CPG-2023-008",
        "citizenName": "Suresh Reddy",
        "department": "MoHFW",
        "subject": "Shortage of ess...",
        "category": "Health",
        "description": "Shortage of essential medicines. Urgent attention needed in Ward 5 area near the local landmark.",
        "location": "Gachibowli",
        "ward": "Ward 8",
        "dateFiled": "21/10/23",
        "status": "Escalated",
        "lastAction": "Verify"
    },
    {
        "id": "CPG-2023-009",
        "citizenName": "Ramesh Kumar",
        "department": "MoRD",
        "subject": "Frequent power ...",
        "category": "Electricity",
        "description": "Frequent power cuts during night. Urgent attention needed in Gachibowli area near the local landmark.",
        "location": "Ward 5",
        "ward": "Ward 10",
        "dateFiled": "21/10/23",
        "status": "Resolved",
        "lastAction": "Escalated"
    },
    {
        "id": "CPG-2023-010",
        "citizenName": "Amit Sharma",
        "department": "MoHFW",
        "subject": "Shortage of ess...",
        "category": "Health",
        "description": "Shortage of essential medicines. Urgent attention needed in Powai area near the local landmark.",
        "location": "Salt Lake",
        "ward": "Ward 14",
        "dateFiled": "21/10/23",
        "status": "Escalated",
        "lastAction": "Assign"
    },
    {
        "id": "CPG-2023-011",
        "citizenName": "Meena Iyer",
        "department": "MoRD",
        "subject": "Contaminated wa...",
        "category": "Water Supply",
        "description": "Contaminated water supply reported. Urgent attention needed in Kailash Colony area near the local landmark.",
        "location": "Powai",
        "ward": "Ward 14",
        "dateFiled": "21/10/23",
        "status": "Pending",
        "lastAction": "Escalated"
    },
    {
        "id": "CPG-2023-012",
        "citizenName": "Sunita Rao",
        "department": "MoRD",
        "subject": "Water pipeline ...",
        "category": "Water Supply",
        "description": "Water pipeline leakage causing flood. Urgent attention needed in Kailash Colony area near the local landmark.",
        "location": "Indiranagar",
        "ward": "Ward 8",
        "dateFiled": "21/10/23",
        "status": "Escalated",
        "lastAction": "Escalated"
    },
    {
        "id": "CPG-2023-013",
        "citizenName": "Rakesh Verma",
        "department": "MoRD",
        "subject": "Verification of...",
        "category": "Pensions",
        "description": "Verification of life certificate pending. Urgent attention needed in Gachibowli area near the local landmark.",
        "location": "Salt Lake",
        "ward": "Ward 14",
        "dateFiled": "21/10/23",
        "status": "Resolved",
        "lastAction": "Resolved"
    },
    {
        "id": "CPG-2023-014",
        "citizenName": "Anjali Gupta",
        "department": "MoRD",
        "subject": "Contaminated wa...",
        "category": "Water Supply",
        "description": "Contaminated water supply reported. Urgent attention needed in Gachibowli area near the local landmark.",
        "location": "Ward 8",
        "ward": "Ward 12",
        "dateFiled": "21/10/23",
        "status": "Pending",
        "lastAction": "Verify"
    },
    {
        "id": "CPG-2023-015",
        "citizenName": "Meena Iyer",
        "department": "MoRD",
        "subject": "Deep potholes o...",
        "category": "Infrastructure",
        "description": "Deep potholes on main road. Urgent attention needed in Indiranagar area near the local landmark.",
        "location": "Ward 12",
        "ward": "Ward 10",
        "dateFiled": "21/10/23",
        "status": "Escalated",
        "lastAction": "Escalated"
    },
    {
        "id": "CPG-2023-016",
        "citizenName": "Ramesh Kumar",
        "department": "MoE",
        "subject": "Primary school ...",
        "category": "Education",
        "description": "Primary school building needs repair. Urgent attention needed in Ward 12 area near the local landmark.",
        "location": "Ward 5",
        "ward": "Ward 11",
        "dateFiled": "21/10/23",
        "status": "Processing",
        "lastAction": "Resolved"
    },
    {
        "id": "CPG-2023-017",
        "citizenName": "Suresh Reddy",
        "department": "MoRD",
        "subject": "Water pipeline ...",
        "category": "Water Supply",
        "description": "Water pipeline leakage causing flood. Urgent attention needed in Powai area near the local landmark.",
        "location": "Ward 12",
        "ward": "Ward 6",
        "dateFiled": "21/10/23",
        "status": "Pending",
        "lastAction": "Assign"
    },
    {
        "id": "CPG-2023-018",
        "citizenName": "Meena Iyer",
        "department": "MoHFW",
        "subject": "Shortage of ess...",
        "category": "Health",
        "description": "Shortage of essential medicines. Urgent attention needed in Indiranagar area near the local landmark.",
        "location": "Ward 8",
        "ward": "Ward 10",
        "dateFiled": "21/10/23",
        "status": "Processing",
        "lastAction": "Escalated"
    },
    {
        "id": "CPG-2023-019",
        "citizenName": "Sunita Rao",
        "department": "MoHFW",
        "subject": "Vaccine deliver...",
        "category": "Health",
        "description": "Vaccine delivery delay. Urgent attention needed in Salt Lake area near the local landmark.",
        "location": "Ward 12",
        "ward": "Ward 4",
        "dateFiled": "21/10/23",
        "status": "Pending",
        "lastAction": "Verify"
    },
    {
        "id": "CPG-2023-020",
        "citizenName": "Vikram Malhotra",
        "department": "MoRD",
        "subject": "Contaminated wa...",
        "category": "Water Supply",
        "description": "Contaminated water supply reported. Urgent attention needed in Kailash Colony area near the local landmark.",
        "location": "Ward 8",
        "ward": "Ward 14",
        "dateFiled": "21/10/23",
        "status": "Resolved",
        "lastAction": "Resolved"
    },
    {
        "id": "CPG-2023-021",
        "citizenName": "Amit Sharma",
        "department": "MoHFW",
        "subject": "Vaccine deliver...",
        "category": "Health",
        "description": "Vaccine delivery delay. Urgent attention needed in Ward 12 area near the local landmark.",
        "location": "Kailash Colony",
        "ward": "Ward 13",
        "dateFiled": "21/10/23",
        "status": "Processing",
        "lastAction": "Escalated"
    },
    {
        "id": "CPG-2023-022",
        "citizenName": "Anjali Gupta",
        "department": "MoRD",
        "subject": "Deep potholes o...",
        "category": "Infrastructure",
        "description": "Deep potholes on main road. Urgent attention needed in Ward 5 area near the local landmark.",
        "location": "Salt Lake",
        "ward": "Ward 2",
        "dateFiled": "21/10/23",
        "status": "Pending",
        "lastAction": "Escalated"
    },
    {
        "id": "CPG-2023-023",
        "citizenName": "Priya Singh",
        "department": "MoRD",
        "subject": "Street light tr...",
        "category": "Electricity",
        "description": "Street light transformer failure. Urgent attention needed in Salt Lake area near the local landmark.",
        "location": "Gachibowli",
        "ward": "Ward 2",
        "dateFiled": "21/10/23",
        "status": "Resolved",
        "lastAction": "Assign"
    },
    {
        "id": "CPG-2023-024",
        "citizenName": "Suresh Reddy",
        "department": "MoHFW",
        "subject": "Vaccine deliver...",
        "category": "Health",
        "description": "Vaccine delivery delay. Urgent attention needed in Ward 12 area near the local landmark.",
        "location": "Salt Lake",
        "ward": "Ward 17",
        "dateFiled": "21/10/23",
        "status": "Pending",
        "lastAction": "Resolved"
    },
    {
        "id": "CPG-2023-025",
        "citizenName": "Vikram Malhotra",
        "department": "MoRD",
        "subject": "Deep potholes o...",
        "category": "Infrastructure",
        "description": "Deep potholes on main road. Urgent attention needed in Powai area near the local landmark.",
        "location": "Gachibowli",
        "ward": "Ward 10",
        "dateFiled": "21/10/23",
        "status": "Pending",
        "lastAction": "Verify"
    },
    {
        "id": "CPG-2023-026",
        "citizenName": "Sunita Rao",
        "department": "MoRD",
        "subject": "Street light tr...",
        "category": "Electricity",
        "description": "Street light transformer failure. Urgent attention needed in Indiranagar area near the local landmark.",
        "location": "Ward 8",
        "ward": "Ward 13",
        "dateFiled": "21/10/23",
        "status": "Escalated",
        "lastAction": "Assign"
    },
    {
        "id": "CPG-2023-027",
        "citizenName": "Rakesh Verma",
        "department": "MoHFW",
        "subject": "Vaccine deliver...",
        "category": "Health",
        "description": "Vaccine delivery delay. Urgent attention needed in Ward 8 area near the local landmark.",
        "location": "Ward 8",
        "ward": "Ward 5",
        "dateFiled": "21/10/23",
        "status": "Resolved",
        "lastAction": "Escalated"
    },
    {
        "id": "CPG-2023-028",
        "citizenName": "Ramesh Kumar",
        "department": "MoRD",
        "subject": "Verification of...",
        "category": "Pensions",
        "description": "Verification of life certificate pending. Urgent attention needed in Gachibowli area near the local landmark.",
        "location": "Ward 8",
        "ward": "Ward 4",
        "dateFiled": "21/10/23",
        "status": "Resolved",
        "lastAction": "Verify"
    },
    {
        "id": "CPG-2023-029",
        "citizenName": "Rakesh Verma",
        "department": "MoRD",
        "subject": "Deep potholes o...",
        "category": "Infrastructure",
        "description": "Deep potholes on main road. Urgent attention needed in Indiranagar area near the local landmark.",
        "location": "Indiranagar",
        "ward": "Ward 13",
        "dateFiled": "21/10/23",
        "status": "Processing",
        "lastAction": "Resolved"
    },
    {
        "id": "CPG-2023-030",
        "citizenName": "Sunita Rao",
        "department": "MoHFW",
        "subject": "Vaccine deliver...",
        "category": "Health",
        "description": "Vaccine delivery delay. Urgent attention needed in Kailash Colony area near the local landmark.",
        "location": "Ward 8",
        "ward": "Ward 3",
        "dateFiled": "21/10/23",
        "status": "Escalated",
        "lastAction": "Escalated"
    },
    {
        "id": "CPG-2023-031",
        "citizenName": "Vikram Malhotra",
        "department": "MoRD",
        "subject": "Monthly pension...",
        "category": "Pensions",
        "description": "Monthly pension not credited. Urgent attention needed in Gachibowli area near the local landmark.",
        "location": "Gachibowli",
        "ward": "Ward 3",
        "dateFiled": "21/10/23",
        "status": "Resolved",
        "lastAction": "Verify"
    },
    {
        "id": "CPG-2023-032",
        "citizenName": "Meena Iyer",
        "department": "MoRD",
        "subject": "Water pipeline ...",
        "category": "Water Supply",
        "description": "Water pipeline leakage causing flood. Urgent attention needed in Indiranagar area near the local landmark.",
        "location": "Gachibowli",
        "ward": "Ward 6",
        "dateFiled": "21/10/23",
        "status": "Resolved",
        "lastAction": "Assign"
    },
    {
        "id": "CPG-2023-033",
        "citizenName": "Deepak Patil",
        "department": "MoRD",
        "subject": "Monthly pension...",
        "category": "Pensions",
        "description": "Monthly pension not credited. Urgent attention needed in Kailash Colony area near the local landmark.",
        "location": "Powai",
        "ward": "Ward 1",
        "dateFiled": "21/10/23",
        "status": "Pending",
        "lastAction": "Resolved"
    },
    {
        "id": "CPG-2023-034",
        "citizenName": "Vikram Malhotra",
        "department": "MoRD",
        "subject": "Verification of...",
        "category": "Pensions",
        "description": "Verification of life certificate pending. Urgent attention needed in Ward 12 area near the local landmark.",
        "location": "Ward 8",
        "ward": "Ward 4",
        "dateFiled": "21/10/23",
        "status": "Pending",
        "lastAction": "Resolved"
    },
    {
        "id": "CPG-2023-035",
        "citizenName": "Rakesh Verma",
        "department": "MoRD",
        "subject": "Street light tr...",
        "category": "Electricity",
        "description": "Street light transformer failure. Urgent attention needed in Ward 8 area near the local landmark.",
        "location": "Powai",
        "ward": "Ward 17",
        "dateFiled": "21/10/23",
        "status": "Resolved",
        "lastAction": "Escalated"
    },
    {
        "id": "CPG-2023-036",
        "citizenName": "Amit Sharma",
        "department": "MoRD",
        "subject": "Verification of...",
        "category": "Pensions",
        "description": "Verification of life certificate pending. Urgent attention needed in Salt Lake area near the local landmark.",
        "location": "Gachibowli",
        "ward": "Ward 7",
        "dateFiled": "21/10/23",
        "status": "Processing",
        "lastAction": "Verify"
    },
    {
        "id": "CPG-2023-037",
        "citizenName": "Sunita Rao",
        "department": "MoRD",
        "subject": "Deep potholes o...",
        "category": "Infrastructure",
        "description": "Deep potholes on main road. Urgent attention needed in Ward 5 area near the local landmark.",
        "location": "Ward 8",
        "ward": "Ward 14",
        "dateFiled": "21/10/23",
        "status": "Resolved",
        "lastAction": "Assign"
    },
    {
        "id": "CPG-2023-038",
        "citizenName": "Priya Singh",
        "department": "MoRD",
        "subject": "Water pipeline ...",
        "category": "Water Supply",
        "description": "Water pipeline leakage causing flood. Urgent attention needed in Gachibowli area near the local landmark.",
        "location": "Kailash Colony",
        "ward": "Ward 2",
        "dateFiled": "21/10/23",
        "status": "Escalated",
        "lastAction": "Verify"
    },
    {
        "id": "CPG-2023-039",
        "citizenName": "Suresh Reddy",
        "department": "MoRD",
        "subject": "Street light tr...",
        "category": "Electricity",
        "description": "Street light transformer failure. Urgent attention needed in Indiranagar area near the local landmark.",
        "location": "Salt Lake",
        "ward": "Ward 8",
        "dateFiled": "21/10/23",
        "status": "Pending",
        "lastAction": "Verify"
    },
    {
        "id": "CPG-2023-040",
        "citizenName": "Ramesh Kumar",
        "department": "MoRD",
        "subject": "Structural crac...",
        "category": "Infrastructure",
        "description": "Structural cracks on flyover. Urgent attention needed in Gachibowli area near the local landmark.",
        "location": "Powai",
        "ward": "Ward 3",
        "dateFiled": "21/10/23",
        "status": "Escalated",
        "lastAction": "Assign"
    },
    {
        "id": "CPG-2023-041",
        "citizenName": "Priya Singh",
        "department": "MoRD",
        "subject": "Deep potholes o...",
        "category": "Infrastructure",
        "description": "Deep potholes on main road. Urgent attention needed in Ward 8 area near the local landmark.",
        "location": "Kailash Colony",
        "ward": "Ward 11",
        "dateFiled": "21/10/23",
        "status": "Processing",
        "lastAction": "Escalated"
    },
    {
        "id": "CPG-2023-042",
        "citizenName": "Anjali Gupta",
        "department": "MoE",
        "subject": "Scholarship pen...",
        "category": "Education",
        "description": "Scholarship pending since last semester. Urgent attention needed in Salt Lake area near the local landmark.",
        "location": "Ward 12",
        "ward": "Ward 18",
        "dateFiled": "21/10/23",
        "status": "Escalated",
        "lastAction": "Escalated"
    },
    {
        "id": "CPG-2023-043",
        "citizenName": "Priya Singh",
        "department": "MoRD",
        "subject": "Frequent power ...",
        "category": "Electricity",
        "description": "Frequent power cuts during night. Urgent attention needed in Ward 5 area near the local landmark.",
        "location": "Ward 8",
        "ward": "Ward 16",
        "dateFiled": "21/10/23",
        "status": "Escalated",
        "lastAction": "Escalated"
    },
    {
        "id": "CPG-2023-044",
        "citizenName": "Rakesh Verma",
        "department": "MoRD",
        "subject": "Contaminated wa...",
        "category": "Water Supply",
        "description": "Contaminated water supply reported. Urgent attention needed in Indiranagar area near the local landmark.",
        "location": "Ward 8",
        "ward": "Ward 13",
        "dateFiled": "21/10/23",
        "status": "Pending",
        "lastAction": "Assign"
    },
    {
        "id": "CPG-2023-045",
        "citizenName": "Suresh Reddy",
        "department": "MoHFW",
        "subject": "Vaccine deliver...",
        "category": "Health",
        "description": "Vaccine delivery delay. Urgent attention needed in Indiranagar area near the local landmark.",
        "location": "Ward 12",
        "ward": "Ward 14",
        "dateFiled": "21/10/23",
        "status": "Processing",
        "lastAction": "Resolved"
    },
    {
        "id": "CPG-2023-046",
        "citizenName": "Rakesh Verma",
        "department": "MoRD",
        "subject": "Structural crac...",
        "category": "Infrastructure",
        "description": "Structural cracks on flyover. Urgent attention needed in Ward 5 area near the local landmark.",
        "location": "Ward 12",
        "ward": "Ward 19",
        "dateFiled": "21/10/23",
        "status": "Resolved",
        "lastAction": "Resolved"
    },
    {
        "id": "CPG-2023-047",
        "citizenName": "Priya Singh",
        "department": "MoRD",
        "subject": "Deep potholes o...",
        "category": "Infrastructure",
        "description": "Deep potholes on main road. Urgent attention needed in Gachibowli area near the local landmark.",
        "location": "Salt Lake",
        "ward": "Ward 11",
        "dateFiled": "21/10/23",
        "status": "Resolved",
        "lastAction": "Resolved"
    },
    {
        "id": "CPG-2023-048",
        "citizenName": "Sunita Rao",
        "department": "MoHFW",
        "subject": "Vaccine deliver...",
        "category": "Health",
        "description": "Vaccine delivery delay. Urgent attention needed in Gachibowli area near the local landmark.",
        "location": "Gachibowli",
        "ward": "Ward 14",
        "dateFiled": "21/10/23",
        "status": "Resolved",
        "lastAction": "Assign"
    },
    {
        "id": "CPG-2023-049",
        "citizenName": "Rakesh Verma",
        "department": "MoRD",
        "subject": "Water pipeline ...",
        "category": "Water Supply",
        "description": "Water pipeline leakage causing flood. Urgent attention needed in Ward 5 area near the local landmark.",
        "location": "Ward 8",
        "ward": "Ward 8",
        "dateFiled": "21/10/23",
        "status": "Resolved",
        "lastAction": "Escalated"
    },
    {
        "id": "CPG-2023-050",
        "citizenName": "Anjali Gupta",
        "department": "MoRD",
        "subject": "Deep potholes o...",
        "category": "Infrastructure",
        "description": "Deep potholes on main road. Urgent attention needed in Indiranagar area near the local landmark.",
        "location": "Powai",
        "ward": "Ward 19",
        "dateFiled": "21/10/23",
        "status": "Escalated",
        "lastAction": "Assign"
    }
];
